# Generated by Django 2.0.3 on 2018-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='KZT', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(max_length=50),
        ),
    ]
